### ISSUE TITLE
Languages selected differ between transcript and caption buttons

### ISSUE THREAD

**Issue by bryanlandia** [raccoongang/xblock-video#292]
Introduced in 0.9.4

Not a major issue, but whichever language is last selected from either the caption hover menu or transcript hover menu will determine the language of both captions and transcript.  But the selected value may still show a different value from what actually appears in the captions and transcript.

In this, the menu shows Spanish selected while the captions and transcript are in French.

![screen shot 2018-01-19 at 5 14 49 pm](https://user-images.githubusercontent.com/1289191/35178302-52292136-fd3c-11e7-8ca1-2b73cd12f08c.png)

@wowkalucky

**Comment by wowkalucky** [comment]
@bryanlandia seems like we don't track active language for transcripts/captions at all.
So, there are two options:
- we simply do not highlight currently active language (if it doesn't hurt UX critically);
- or we need to implement all that state-tracking stuff;
?

**Comment by bryanlandia** [comment]
@wowkalucky - Let's not highlight active language for now.  This could be a nice to have.

**Comment by bryanlandia** [comment]
Great, this is fixed in 0.10.0.  Closing this.
