### ISSUE TITLE
The Video XBlock isn't compatible with Hawthorn

### ISSUE THREAD

**Issue by OmarIthawi** [raccoongang/xblock-video#323]
The current XBlock version (as of writing this issue) breaks the Hawthorn edxapp when installed. Mainly because it requires installing `pycaptions`. 

`pycaptions` isn't maintained anymore and depends on and and conflicting requirements such as:
 - `lxml`
 - `beautifulsoup4`
 - and others

I tried to upgrade `pycaptions` but stopped after realizing that it's not maintained anymore:

 - https://github.com/pbs/pycaption/pull/178

I also found that `webvtt-py` could be used, but it turns out that it only support Python 3+. I tried to support that as well:

 - https://github.com/glut23/webvtt-py/pull/15

Oh, I didn't also mention that this XBlock needs a couple of updates to the XBlock to make it render:
 - https://github.com/appsembler/xblock-video/pull/29

Needless to say it was a rabbit hole. I surrender with honor. I would appreciate it if you can take a look.

**Comment by OmarIthawi** [comment]
@z4y4ts @wowkalucky @bryanlandia fyi.

**Comment by z4y4ts** [comment]
Hi @OmarIthawi, sorry to hear your sufferings. Lack of Python 3 support makes life miserable indeed.
Unfortunately, I can't help you here, because I no longer work on this project for a quite some time.
But other guys might be able to help you.

If you still need help here, of course.
