### ISSUE TITLE
Rendering of Django templates fails in Ironwood after a video_xblock is rendered

### ISSUE THREAD

**Issue by matthewf-ucsd** [raccoongang/xblock-video#402]
We have two significant pages that are rendered using django templates in our Ironwood environment, the logout page and the 'reset your password' reminder email. After a request for a page that includes a video-xblock from the ironwood-rg branch has been responded to, the responding process no longer renders other django templates correctly, because utils.py:render_template() modifies engine.dirs with the path to its own templates.

**Comment by GlugovGrGlib** [comment]
Thanks for reporting, fixed with #410
