### ISSUE TITLE
Video Play action is not recorded in the analytics logs

### ISSUE THREAD

**Issue by pamhristova** [raccoongang/xblock-video#483]
The Video Play action is not recorded in the analytics logs. 
Therefore, the analytics reporting does not display/track that the video is played. 

1.	On debug in the browser, the listener creates log for the play video action, but in the network, there is no request to the server. We have detected that there is a mismatch between the expected id in the URL and what is received.
For Example - Expected: "4752cd6b461d45f8aa7b69433dfd677e"
Received:”block-v1:Rushmore+RC001+2021_T4+type@video_xblock+block@4752cd6b461d45f8aa7b69433dfd677e”

2.	Also, for comparison:
the standard Open EdX x-blocks log the actions via **Logger.log**(eventName, logInfo);
where here, it is implemented with: 
 this.log = function(eventName, data) {
            var xblockUsageId = getXblockUsageId();
            data = data || {};  //  eslint-disable-line no-param-reassign
            data.eventType = 'xblock-video.' + eventName;  //  eslint-disable-line no-param-reassign
            **parent.postMessage({
                action: 'analytics',
                info: data,
                xblockUsageId: xblockUsageId
            }, document.location.protocol + '//' + document.location.host);**
        };

**Comment by andrewhippo3** [comment]
Hi, @pamhristova!
Thank for your contribution. I've created a task to investigate the issue. We will return with updates after its completing.

**Comment by idegtiarov** [comment]
Closed by #688
