### ISSUE TITLE
With Brightcove - the played displays 2 play buttons

### ISSUE THREAD

**Issue by pamhristova** [raccoongang/xblock-video#484]
![brightcove-douple play buttons](https://user-images.githubusercontent.com/71934054/148958980-1e9d9895-8748-4b80-9156-de8dac841453.png)

This issue has been already discussed here(https://github.com/appsembler/xblock-video/issues/27)

**Comment by andrewhippo3** [comment]
Hi, @pamhristova. Thanks for your contribution. The problem isn't actual now. Brightcove provider has the same UI appearance as the default view.
![image](https://user-images.githubusercontent.com/87175607/229049823-9fa95807-ac83-4196-bb27-dadb786ffaa2.png)
